### ISSUE TITLE
Config and serialization issues (catch-all)

### ISSUE THREAD

**Issue by rusheb** [AISC-understanding-search/maze-transformer#117]
This is a catch-all ticket to store all config and serialization issues. We plan to come back to these once we have a working model. 

- Tokenizer is not serialized on the ConfigHolder
- ConfigHolder modifies its own state (self.tokenizer property) when calling `create_model`
- Generating a MazeDatasetConfig just to extract `node_token_map` (issue #77)
- Having to construct a ConfigHolder just to create the MazeTokenizer
- In research code, we want one flat config that we can pass around everywhere, rather than having to deal with multiple different types of config
- coupling between configs e.g. how the model vocab size is determined by the dataset
- at dataset creation time we need just dataset config but at model training time we need all configs
- Each member of ConfigHolder may or may not be there at a given stage...for example when creating a dataset there is no model. Seems like a smell
- Inconsistency between wandb config  (`ConfigHolder.serialize()` passed to `wandb.init`) and ConfigHolder which is passed through the `train` function
- In `data` dir, there are two files, where `cfg.json` is a subset of `config.json`. Can `cfg.json` be removed?

**Comment by mivanit** [comment]
- [x] port `ConfigHolder` to muutils `SerializableDataclass` (done in #139)
   - [x] tokenizer serialization handled here as well
- [ ] config coupling:
   - [ ] remove the need to generate `MazeDatasetConfig` just to get the tokenizer? I'm not sure if this actually makes sense, since the tokenizer definitely depends on the config. maybe a class method which just instantiates config, returns tokenizer, and throws the rest away?
   - [~] "how the model vocab size is determined by the dataset" this makes sense though? I'm not sure how to get around this
   - [ ] handling cases where only part of the `ConfigHolder` exists
- [ ] structure of `data` dir: should be resolved in next ZANJ-integration PR which will migrate datasets


# Other things:
- "Inconsistency between wandb config (ConfigHolder.serialize() passed to wandb.init) and ConfigHolder which is passed through the train function":
   `ConfigHolder().serialize()` created a dict which can be stored to json, in such a way that `ConfigHolder.load(data)` recovers it perfectly as an object. wandb puts these things in YAML files but modifies the structure, and I don't know how to get around this. This will partially be resolved by #157 and the next PR which will implement saving/loading datasets with ZANJ, since the dataset will contain the config in our json format.
- "one flat config that we can pass around everywhere" -- this should be the `ConfigHolder`. passing a flat config is now possible through methods in `muutils.dictmagic` but is probably not good unless its for human readability.

**Comment by mivanit** [comment]
- `ConfigHolder` and the sub-configs now have `.summary()` function to generate a mostly-flat and human-readable dict
- `maze_tokenizer` attribute of `ConfigHolder` is much clearer than the old ways and is serialized properly
  - dataset config creation no longer needed for tokenizer, just a tokenization mode and maximum maze size
  - if `maze_tokenizer` attribute has no max size, `ConfigHolder.__post_init__()` handles it
- model and training run storage now done fully via zanj


wandb stuff is still an issue, but that should be a different catch-all issue
