### ISSUE TITLE
Store datasets in raw format rather than as tokens

### ISSUE THREAD

**Issue by rusheb** [AISC-understanding-search/maze-transformer#137]
Storing the dataset as tokens is leading to coupling and inflexibility. In particular, it means that
- The dataset is coupled to the tokenization scheme, making it difficult to support different tokenization schemes
- The model config is coupled to the dataset config

We could improve this by storing the dataset in a canonical format and choosing a tokenization scheme to convert to when feeding it to the model. This would allow us to simplify the dataset config. 

We should think about whether this would make it challenging to visualise datasets. We should also consider compatibility issues.

**Comment by mivanit** [comment]
I think this is a good idea!

In the zanj integration PR #139, I refactored the tokenizer as follows: instead of being a member, it's a (cached) property which is constructed from either:
- passing `ConfigHolder().pretrainedtokenizer_kwargs` to `PreTrainedTokenizer` if the former is not `None`
- creating a `HuggingMazeTokenizer` from the `ConfigHolder().dataset_cfg` otherwise

The `HuggingMazeTokenizer` currently takes a dataset config, or optionally just the `token_arr` and `seq_len_max`, which are the only two things from the dataset config which are actually used. One option for how to make this work is just to have a tokenizer config member of the `ConfigHolder`, which would contain the `token_arr` and be passed when creating the tokenizer.

`seq_len_max` might actually depend on the dataset sometimes, so I'm not too sure what to do about that.

Also, we do rely on getting tokenizer-related things from the dataset config at a number of places in the code -- we could refactor all these, or we could add a compatibility layer where `MazeDatasetConfig` gets the `token_arr` from it's parent `ConfigHolder`.

**Comment by mivanit** [comment]
completed in #177
