### ISSUE TITLE
Handle serialization/loading of ConfigHolder with missing values

### ISSUE THREAD

**Issue by rusheb** [AISC-understanding-search/maze-transformer#25]
If ConfigHolder has missing values it will fail to serialize, as demonstrated in [test_serialize_and_load_missing_values](https://github.com/AISC-understanding-search/maze-transformer/blob/eed70557a7fc9d697e5c0d53231504a1ad320134/tests/unit/maze_transformer/training/config/test_config_holder.py#L41).

This might be an issue if we don't have all the configs, e.g. at the dataset creation stage.

However maybe at that point we wouldn't serialize the entire config. I'm not sure what the best behaviour should be

**Comment by valedan** [comment]
This isn't causing any problems currently because during dataset creation we don't use `ConfigHolder`, just the dataset config. 

I'm not really sure what our long-term plans are with configs and `ConfigHolder` specifically, so I can't say if this is something we should work on or not. @mivanit do you have any input here?

**Comment by valedan** [comment]
Sounds reasonable. In that case the only TODO for this ticket would be to delete the test that @rusheb linked.

**Comment by mivanit** [comment]
I haven't had any issues with this for a while, despite several changes to the `ConfigHolder` (i.e. `maze_tokenizer` attr in #191 ). Key point is to make sure you allow for missing values in the `loading_fn`
